version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_fast_api
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
